qa/urls.py
from django.conf.urls.defaults import patterns, url
from .views import *
from qa.sitemaps import sitemaps

urlpatterns = patterns('qa.views',
    url(r'^(?P<entity_slug>.*)/qna/post_q/$', 'post_question', name='post_question'),
    url(r'^post_q_router/$', 'post_q_router', name='post_q_router'),
    url(r'^(?P<entity_slug>[-\w]+)/qna/(?P<slug>[-\w]+)/edit$', 'post_question', name='edit_question'),
    url(r'^(?P<entity_slug>[-\w]+)/qna/(?P<slug>[-\w]+)/$',
        QuestionDetail.as_view(),
        name='question_detail'
    ),
    url(r'^(?P<entity_id>[-\d]+)/qna/$', 'questions', name='qna'),
    url(r'^(?P<entity_slug>[-\w]+)/qna/$', 'questions', name='qna'),
    url(r'^(?P<entity_slug>[-\w]+)/qna/tags/(?P<tags>.+)/$', 'questions', name='show_tags'),

    url(r'^qna/post_a/(?P<q_id>\d+)/$', 'post_answer', name='post_answer'),

	url(r'^qna/flag_question/(?P<q_id>\d+)/flag/$', 'flag_question', name='flag_question'),

    url(r'upvote_question/(?P<q_id>\d+)/$', 'upvote_question', name='upvote_question'),
)

urlpatterns += patterns('',
    (r'^sitemap\.xml$',
        'django.contrib.sitemaps.views.index',
        {'sitemaps': sitemaps}
    ),

    (r'^sitemap-(?P<section>.+)\.xml$',
        'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': sitemaps}
    ),

    url(r'^qna/rss/$',
        RssQuestionFeed(),
        name='rss_all_questions'
    ),

    url(r'^(?P<entity>.*)/qna/atom/$',
        AtomQuestionFeed(),
        name='atom_entity_questions'
    ),

    url(r'^atom/$',
        AtomQuestionFeed(),
        name='atom_all_questions'
    ),

    url(r'^q/(?P<q_id>\d+)/rss/answers/$',
        RssQuestionAnswerFeed(),
        name='rss_question_answers'
    ),

    url(r'^q/(?P<q_id>\d+)/atom/answers/$',
        AtomQuestionAnswerFeed(),
        name='atom_question_answers'
    ),
)

qa/models.py
from django.db import models, transaction
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.contrib.sites.managers import CurrentSiteManager
from django.utils.translation import ugettext as _
from django.core.urlresolvers import reverse
from taggit.models import TaggedItemBase
from slugify import slugify as unislugify
from taggit_autosuggest.managers import TaggableManager
from entities.models import Entity


MAX_LENGTH_Q_SUBJECT = 140
MAX_LENGTH_Q_CONTENT = 255
MAX_LENGTH_A_SUBJECT = 80
MAX_LENGTH_A_CONTENT = 500

class BaseModel(models.Model):
    ''' just a common time base for the models
    '''
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# TODO: next class looks silly, do we really need it?
class TaggedQuestion(TaggedItemBase):
    content_object = models.ForeignKey("Question")
    sites = models.ManyToManyField(Site)
    # objects = models.Manager()
    # objects = CurrentSiteManager()

class Question(BaseModel):

    # TODO: rename to just `slug`
    unislug = models.CharField(
        _('unicode slug'),
        max_length=MAX_LENGTH_Q_SUBJECT,
        null=True,
        blank=True,
        editable=False
    )
    author = models.ForeignKey(User, related_name="questions", verbose_name=_("author"))
    subject = models.CharField(_("question"), max_length=MAX_LENGTH_Q_SUBJECT)
    content = models.TextField(_("details"), max_length=MAX_LENGTH_Q_CONTENT,
       help_text=_("Please enter your content in no more than %s letters") % MAX_LENGTH_Q_CONTENT,
       blank = True, default = '')
    rating = models.IntegerField(_("rating"), default=1)
    flags_count = models.IntegerField(_("flags counter"), default=0)
    tags = TaggableManager(through=TaggedQuestion)
    # tags = TaggableManager(through=TaggedQuestion, blank=True)
    sites = models.ManyToManyField(Site)
    # for easy access to current site questions
    objects = models.Manager()
    on_site = CurrentSiteManager()
    entity = models.ForeignKey(Entity, null=True, related_name="questions")

    class Meta:
        unique_together = ('unislug','entity')

    def __unicode__(self):
        return self.subject

    def can_answer(self, user):
        ''' Can a given user answer self? '''
        if user.is_authenticated():
            profile = user.profile
            return profile.is_candidate and profile.locality==self.entity
        else:
            return False

    def get_absolute_url(self):
        return reverse('question_detail', kwargs=dict(
                            entity_slug=self.entity.slug,
                            slug=self.unislug,
                            )
                      )

    def save(self, **kwargs):
        # make a unicode slug from the subject
        self.unislug = unislugify(self.subject)
        return super(Question, self).save(**kwargs)

    @transaction.commit_on_success
    def flagged(self):
        self.flags_count += 1
        self.save()
        return self.flags_count


class Answer(BaseModel):
    author = models.ForeignKey(User, related_name="answers", verbose_name=_("author"))
    content = models.TextField(_("content"), max_length=MAX_LENGTH_A_CONTENT,
        help_text=_("Please enter an answer in no more than %s letters") % MAX_LENGTH_A_CONTENT)
    rating = models.IntegerField(_("rating"), default=0)
    question = models.ForeignKey(Question, related_name="answers", verbose_name=_("question"))
    sites = models.ManyToManyField(Site)
    # for easy access to current site answers
    objects = models.Manager()
    on_site = CurrentSiteManager()

    def __unicode__(self):
        return "%s: %s" % (self.author, self.content[:30])

    def get_absolute_url(self):
        return '%s#answer-%s' % (self.question.get_absolute_url(), self.id)

class QuestionUpvote(BaseModel):
    question = models.ForeignKey(Question, related_name="upvotes")
    user = models.ForeignKey(User, related_name="upvotes")

class QuestionFlag(BaseModel):
    question = models.ForeignKey(Question, related_name="flags")
    reporter = models.ForeignKey(User, related_name="flags")

''' signals code, to ensure correct site is saved 
'''
@receiver(post_save)
def saved(sender, created, instance, **kwargs):
    if sender in (Question, Answer, TaggedQuestion):
        instance.sites.add(Site.objects.get_current())

qa/forms.py
from django.forms import ModelForm, TextInput, Textarea, HiddenInput
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext as _

from models import Answer, Question

from slugify import slugify as unislugify


class AnswerForm(ModelForm):
    class Meta:
        model = Answer
        fields = ("content",)


class QuestionForm(ModelForm):

    class Meta:
        model = Question
        # fields = ("subject", "content", "tags", )
        fields = ("subject", "entity")
        widgets = { 'subject': Textarea(attrs={'cols': 70, 'rows': 2}), 
                    'entity': HiddenInput}

    def clean(self):
        cleaned_data = super(QuestionForm, self).clean()
        unislug = unislugify(cleaned_data.get('subject'))
        if Question.objects.filter(entity=cleaned_data['entity']).filter(unislug=unislug):
            raise ValidationError(_("Question already exists."))

        return cleaned_data

    def clean_subject(self):
        subject = self.cleaned_data['subject']
        if subject == 'post_q':
            raise ValidationError(_("Invalid question"))
        return subject

qa/views.py
import json

from django.http import HttpResponse, HttpResponseForbidden
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST
from django.template.context import RequestContext
from django.contrib.auth.decorators import login_required
from django.utils.translation import ugettext as _
from django.contrib.syndication.views import Feed
from django.utils.feedgenerator import Atom1Feed
from django.contrib import messages
from django.conf import settings
from django.views.generic.detail import SingleObjectTemplateResponseMixin, BaseDetailView

from qa.forms import AnswerForm, QuestionForm
from .models import *
from qa.mixins import JSONResponseMixin

from user.views import edit_profile


# the order options for the list views
ORDER_OPTIONS = {'date': '-created_at', 'rating': '-rating'}


class JsonpResponse(HttpResponse):
    def __init__(self, data, callback, *args, **kwargs):
        jsonp = "%s(%s)" % (callback, json.dumps(data))
        super(JsonpResponse, self).__init__(
            content=jsonp,
            content_type='application/javascript',
            *args, **kwargs)


def questions(request, entity_slug=None, entity_id=None, tags=None):
    """
    list questions ordered by number of upvotes
    """

    # TODO: cache the next lines
    if entity_id:
        entity = Entity.objects.get(pk=entity_id)
    else:
        entity = Entity.objects.get(slug=entity_slug)

    questions = Question.on_site.filter(entity=entity)

    context = {'entity': entity}
    order_opt = request.GET.get('order', 'rating')
    order = ORDER_OPTIONS[order_opt]
    if tags:
        tags_list = tags.split(',')
        questions = questions.filter(tags__name__in=tags_list)
        context['current_tags'] = tags_list

    questions = questions.order_by(order)
    # TODO: revive the tags!
    # context['tags'] = TaggedQuestion.on_site.values('tag__name').annotate(count=Count("tag"))

    context['questions'] = questions
    context['by_date'] = order_opt == 'date'
    context['by_rating'] = order_opt == 'rating'
    return render(request, "qa/question_list.html", RequestContext(request, context))


class QuestionDetail(JSONResponseMixin, SingleObjectTemplateResponseMixin, BaseDetailView):
    model = Question
    template_name = 'qa/question_detail.html'
    context_object_name = 'question'
    slug_field = 'unislug'

    def get_context_data(self, **kwargs):
        context = super(QuestionDetail, self).get_context_data(**kwargs)
        context['max_length_a_content'] = MAX_LENGTH_A_CONTENT
        context['answers'] = self.object.answers.all()
        context['entity'] = self.object.entity
        can_answer = self.object.can_answer(self.request.user)
        context['can_answer'] = can_answer
        if can_answer:
            try:
                user_answer = self.object.answers.get(author=self.request.user)
                context['my_answer_form'] = AnswerForm(instance=user_answer)
                context['my_answer_id'] = user_answer.id
            except self.object.answers.model.DoesNotExist:
                context['my_answer_form'] = AnswerForm()

        if self.request.user.is_authenticated() and \
                not self.request.user.upvotes.filter(question=self.object).exists():
            context['can_upvote'] = True
        else:
            context['can_upvote'] = False

        return context

    def render_to_response(self, context):
        # Look for a 'format=json' GET argument
        if self.request.GET.get('format', 'html') == 'json' or self.request.is_ajax():
            data = {
                'question': {
                    'subject': self.object.subject,
                    'content': self.object.content,
                    'author': self.object.author.username
                }
            }

            return JSONResponseMixin.render_to_response(self, data)
        else:
            return SingleObjectTemplateResponseMixin.render_to_response(self, context)


@login_required
def post_answer(request, q_id):
    context = {}
    question = Question.objects.get(id=q_id)

    if not question.can_answer(request.user):
        return HttpResponseForbidden(_("You must be logged in as a candidate to post answers"))

    try:
        # make sure the user haven't answered already
        answer = question.answers.get(author=request.user)
    except question.answers.model.DoesNotExist:
        answer = Answer(author=request.user, question=question)

    answer.content = request.POST.get("content")

    answer.save()
    return HttpResponseRedirect(question.get_absolute_url())


@login_required
def post_q_router(request):
    user = request.user
    if user.is_anonymous():
        return HttpResponseRedirect(settings.LOGIN_URL)
    else:
        profile = user.profile
        entity_slug = profile.locality and profile.locality.slug
        if entity_slug:
            return HttpResponseRedirect(reverse(post_question, args=(entity_slug, )))
        else:
            # user must set locality
            return HttpResponseRedirect(reverse(edit_profile))


@login_required
def post_question(request, entity_slug, slug=None):
    entity = Entity.objects.get(slug=entity_slug)
    if slug:
        q = get_object_or_404(Question, unislug=slug, entity=entity)

    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            if slug:
                if q.author != request.user:
                    return HttpResponseForibdden(_("You can only edit your own questions."))
                if q.answers.count():
                    return HttpResponseForbidden(_("Question has been answered, editing disabled."))
                question = q
                question.subject = form.cleaned_data.get('subject', "")
                question.save()
            else:
                question = form.save(commit=False)
                question.author = request.user
                question.entity = entity
                question.save()
                form.save_m2m()
            return HttpResponseRedirect(question.get_absolute_url())
    else:
        if slug:
            subject = q.subject
        else:
            subject = ""
        form = QuestionForm(initial={'entity': entity, 'subject': subject})

    context = RequestContext(request, {"form": form,
                                       "entity": entity,
                                       "max_length_q_subject": MAX_LENGTH_Q_SUBJECT,
                                       "slug": slug,
    })
    return render(request, "qa/post_question.html", context)


@login_required
def upvote_question(request, q_id):
    if request.method == "POST":
        q = get_object_or_404(Question, id=q_id)
        user = request.user

        if q.author == user or user.upvotes.filter(question=q):
            return HttpResponseForbidden(_("You already upvoted this question"))
        else:
            upvote = QuestionUpvote.objects.create(question=q, user=user)
            #TODO: use signals so the next line won't be necesary
            new_count = increase_rating(q)
            return HttpResponse(new_count)
    else:
        return HttpResponseForbidden(_("Use POST to upvote a question"))


@transaction.commit_on_success
def increase_rating(q):
    q = Question.objects.get(id=q.id)
    q.rating += 1
    q.save()
    return q.rating


class RssQuestionFeed(Feed):
    """Simple feed to get all questions"""
    title = _('OK QA Question Feed')
    link = "/"
    description = _('Questions from OKQA')

    def items(self):
        return Question.objects.order_by('-updated_at')

    def item_title(self, item):
        return item.subject

    def item_description(self, item):
        return item.content


class AtomQuestionFeed(RssQuestionFeed):
    feed_type = Atom1Feed
    subtitle = RssQuestionFeed.description


class RssQuestionAnswerFeed(Feed):
    """"Give question, get all answers for that question"""

    def get_object(self, request, q_id):
        return get_object_or_404(Question, pk=q_id)

    def title(self, obj):
        return _('Answers for the question') + ' "%s' % obj.subject + '"'

    def link(self, obj):
        return obj.get_absolute_url()

    def description(self, obj):
        return _('A feed of all answers for the question') + ' "%s' % obj.subject + '"'

    def items(self, obj):
        return Answer.objects.filter(question=obj).order_by('-updated_at')


class AtomQuestionAnswerFeed(RssQuestionAnswerFeed):
    feed_type = Atom1Feed
    subtitle = RssQuestionAnswerFeed.description


@require_POST
def flag_question(request, q_id):
    q = get_object_or_404(Question, id=q_id)
    user = request.user
    ret = {}
    if user.is_anonymous():
        messages.error(request, _('Sorry, you have to login to flag questions'))
        ret["redirect"] = '%s?next=%s' % (settings.LOGIN_URL, q.get_absolute_url())
    elif (user.profile.is_editor and user.profile.locality == q.entity) or (user == q.author and not q.answers.all()):
        q.delete()
        messages.info(request, _('Question has been removed'))
        ret["redirect"] = reverse('qna', args=(q.entity.slug,))
    elif user.flags.filter(question=q):
        ret["message"] = _('Thanks.  You already reported this question')
    else:
        flag = QuestionFlag.objects.create(question=q, reporter=user)
        #TODO: use signals so the next line won't be necesary
        q.flagged()
        ret["message"] = _('Thank you for falgging the question. One of our editors will look at it shortly.')
    return HttpResponse(json.dumps(ret), content_type="application/json")

qa/templates/qa/_answer.html
{% load i18n %}

{% with author_url=answer.author.get_absolute_url %}
<div id="answer-{{answer.id}}" class="answer" style="min-height: 35px; display: table">
  <div class="avatar-container" style="float:right; padding:6px 10px; display: table-cell; vertical-align: middle;">
    <a href="{{ author_url }}">
    <img class="avatar img-circle" style="width:25px;" src="{{ answer.author.profile.avatar_url|default:'/static/img/defaultavatar.png' }}">
    </a>
  </div>
  <div style="display: table-cell; vertical-align: middle;">
    <div class="answer-text">
      <div>
        <span class="answer-copy">
          {{ answer.content|linebreaksbr }}
        </span>
        –&nbsp;
        <a href="{{ author_url }}" title="{{answer.author.get_full_name}}" rel="tooltip" class="answer-user owner">
          {{answer.author.get_full_name}}
        </a> 
        <span class="answer-date" dir="ltr">
          <a class="answer-link" href="{{answer.get_absolute_url}}">
            <span title="{{answer.updated_at}}" class="relativetime">
              {% trans "before" %} {{ answer.updated_at|timesince }}
            </span>
          </a>
        </span>
        {% if my_answer_id == answer.id %}
        <a id="edit-answer-{{answer.id}}" href="#add_answer_modal" class="edit" rel="tooltip" title="{% trans 'Edit' %}" data-toggle="modal">&#9998; {% trans 'Edit' %}</a>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endwith %}

qa/templates/qa/_question.html
{% load i18n %}
{% load url from future %}
<!-- Let's add the upvote and follow on hover -->
<div class="question-summary narrow" id="question-summary-{{ question.id }}">
    <div class="avatar-container" style="padding-top:15px;">
      <a href="{{ question.author.get_absolute_url }}" rel="tooltip" class="" title="{{question.author.get_full_name}}">
        <img src="{{ question.author.profile.avatar_url|default:'/static/img/defaultavatar.png' }}" width="42" height="42" class="avatar img-circle">
      </a>
    </div>
    <div onclick="window.location.href='{{ question.get_absolute_url }}'" class="cp">
        <div class="votes">
          <div class="mini-counts" id="votes-count-{{question.id}}">{{ question.rating }}</div>
            <div>{% trans "votes" %}</div>
        </div>
        {% with count=question.answers.count %}
          {% if count %}
          <div class="answers" title="">
              <div class="mini-counts">{{ count }}</div>
            <div>{% trans "answers" %}</div>
          </div>
          {% endif %}
        {% endwith %}
    </div>
    <div class="summary">
      <h3><a href="{{ question.get_absolute_url }}" class="question-hyperlink" title="{{ question.subject }}">{{ question.subject }}</a></h3>
        <div class="preview">
            {{ question.content }}
        </div>
        <div class="tags">
          {% for tag in question.tags.all %}
            <a href="{% url 'show_tags' entity tag|urlencode %}">{{tag}}</a>
          {% endfor %}
        </div>
        <div class="started">
            <span title="{{ question.created_at }}" class="relativetime">{% trans "before" %} {{ question.created_at|timesince }}</span>
            <a href="{{ question.author.get_absolute_url }}" rel="tooltip" class="answer-user owner" title="{{question.author.get_full_name}}">{{question.author.get_full_name|default:question.author.username}}</a>
            {% if not entity %}
              {% trans "from"%}
              <a href="{% url "qna" question.entity.slug %}">{{ question.entity }}</a>
            {% endif %}
        </div>
        {% if question.answers.count and show_responders %}        
        <div>
        <div  style="padding-top:15px;">
          <span class="candidates-answered">{% trans "candidates that answered" %}</span>
        </div>
          {% for answer in question.answers.all %}
          <div class="avatar-container" style="padding-top:15px;">
            <a href="{{ answer.author.get_absolute_url }}" rel="tooltip" class="" title="{{answer.author.get_full_name}}">
              <img src="{{ answer.author.profile.avatar_url|default:'/static/img/defaultavatar.png' }}" width="42" height="42" class="avatar img-circle" /><br/>
              <span>{{answer.author.get_full_name}}</span>
            </a>
          </div>
          {% endfor %}
        </div>
        {% endif %}
    </div>
</div>

qa/templates/qa/post_question.html
{% extends "qa/qa_base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block extrahead %}
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/autoSuggest.css"/>
{% endblock %}

{% block mainContainer %}
<div class="page-header">
  {% if not slug %}
    <h1>{% trans "What is your question, sire?" %}</h1>
  {% else %}
    <h1>{% trans "Edit your question" %}</h1>
  {% endif %}
</div>

<form class="form-horizontal" method="POST">
  <div class="row post-question">
    <script src="{{ STATIC_URL }}js/jquery.js"></script>
    <script src="{{ STATIC_URL }}js/jquery.autoSuggest.js"></script>
    {% csrf_token %}
    {{ form|crispy }}
    <div id="charsCounter"><span id="charsLeft"></span> {% trans 'characters left' %}</div>
  </div>
  <div class="row">
    <div class="offset2">
      <button type="submit" class="btn btn-primary">{% trans 'Publish' %}</button>
    </div>
  </div>
</form>
{% endblock %}

{% block extrascript %}
{% if max_length_q_subject %}
    <script>
	var $subject = $("#id_subject"),
	    $charsCounter = $("#charsCounter"),
	    $charsLeft = $("#charsLeft");

	$charsCounter.hide();
	$subject.on("keyup", function () {
	    var length = this.value.length;

	    if (length) $charsCounter.show();
	    else $charsCounter.hide();

	    $charsLeft.text({{ max_length_q_subject }} - length);
	});
    </script>
{% endif %}
{% endblock %}

qa/templates/qa/qa_base.html
{% extends "place_base.html" %}
{% block nav-questions %}class="active"{% endblock %}

qa/templates/qa/question_detail.html
{% extends "qa/qa_base.html" %}
{% load i18n %}
{% block pageTitle %}{{ question }}{% endblock %}
{% block extrahead %}
    <style>
        .question-summary {
            border: 0 none;
        }
    </style>
{% endblock %}
{% block mainContainer %}
    <div class="container">
        <div class="row">
            <div class="span9">
                {% include "qa/_question.html" %}
            </div>
            <div class="span3 sidebar">
                <a class="btn btn-primary"
                   id="upvote-question" href="#">
                    {% trans "I Want an Answer" %}
                </a>
                {% if can_answer %}
                    <a class="btn btn-success btn-large" style="margin-top: 10px;" href="#add_answer_modal"
                       data-toggle="modal">{% trans "Answer the Question" %}</a>
                {% endif %}
                {% if user.profile.is_editor %}
                    <a class="btn btn-danger" href="#remove-question" data-toggle="modal">&#9872; </a>
                    <div id="remove-question" class="modal hide fade">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h3>{% trans "Confirm Question Removal" %}</h3>
                        </div>
                        <div class="modal-body">
                            <blockquote>{{ question }}</blockquote>
                            <p>{% trans "Are you sure you want to remove the question?" %}</p>
                        </div>
                        <div class="modal-footer">
                            <a class="flag-question btn btn-primary" data-dismiss="modal"
                               question-id="{{ question.id }}" href="#">
                                {% trans "Delete" %}
                            </a>
                        </div>
                    </div>
                {% else %}
                    {% if user != question.author or not question.answers.all %}
                    <a class="flag-question btn btn-danger {% if not can_upvote %}disabled{% endif %}"
                       question-id="{{ question.id }}" href="#">
                      {% if user == question.author %}
                      {% trans "Delete" %}
                      {% else %}
                      &#9872;
                      {% endif %}
                    </a>
                    {% endif %}
                {% endif %}
            </div>

        </div>
        <div class="row questions-wrapper">
            <div class="span9 answers">
                {% if answers %}
                    <h5>
                        {% trans 'Answers' %}
                        <div class="pull-right">
                            <a href="{% url "atom_question_answers" question.id %}" title="{% trans 'feed' %}"
                               rel="tooltip">
                                <img src="{{ STATIC_URL }}img/rss.png" width="25"/>
                            </a>
                        </div>
                    </h5>
                {% endif %}

                {% for answer in answers %}
                    {% include "qa/_answer.html" %}
                {% empty %}
                    <h5>{% trans "No Answers Yet" %}
                        <a href="{% url "atom_question_answers" question.id %}" title="{% trans 'Subscribe' %}"
                           rel="tooltip">
                            <!-- <img src="/static/img/social-icons/colour/rss.png" width="25" /> -->
                        </a>
                    </h5>
                {% endfor %}
            </div>
            <div class="span3">

            </div>
        </div>
    </div>
    {% if my_answer_form %}
        <div class="modal fade" id="add_answer_modal">
            <form class="form" method="post" action="{% url "post_answer" question.id %}">
                <div class="modal-header">
                    <a class="close" data-dismiss="modal">&times;</a>

                    <h3>{{ question.subject }}</h3>
                </div>
                <div class="modal-body">
                    {% csrf_token %}
                    {{ my_answer_form.as_p }}
                    <div id="charsCounter"><span id="charsLeft"></span> {% trans 'characters left' %}</div>
                </div>
                <div class="modal-footer">
                    <input type="submit" class="btn btn-primary" value="{% trans "Publish" %}"/>
                </div>
            </form>
        </div>
    {% endif %}
{% endblock %}
{% if my_answer_id %}
    {% block extrascript %}
        <script>
            function display_message(message, level) {
                $("#messages").html('<div class="alert ' + level + '">' +
                        '<button type="button" class="close" data-dismiss="alert">×</button>' +
                        message +
                        '</div>');
            }
            $(document).ready(function () {
                $("#upvote-question").ajaxError(function (evt, jqXHR, setting, err) {
                    $("#messages").html('<div class="alert" class="error">' +
                            '<button type="button" class="close" data-dismiss="alert">×</button>' +
                            jqXHR.responseText + '</div>');
                });

                $("#upvote-question").click(function () {
                    {% if not can_upvote %}
                        $("#messages").html('<div class="alert" class="info">' +
                                '<button type="button" class="close" data-dismiss="alert">×</button>' +
                                "{% trans 'Sorry but only connected users can upvote questions' %}" +
                                '</div>');
                    {% else %}
                        $.post("{% url "upvote_question" question.id %}",
                                {csrfmiddlewaretoken: "{{ csrf_token }}"},
                                function (data, status, jqXHR) {
                                    $("#votes-count-{{question.id}}").html(jqXHR.responseText);
                                });
                    {% endif %}
                    return false;
                })
                $(".flag-question").click(function (e) {
                    var url = "{% url "flag_question" question.id %}";
                    $.ajax({url: url,
                        type: "POST",
                        dataType: "json",
                        data: {csrfmiddlewaretoken: "{{ csrf_token }}"}}).always(
                            function (data, textStatus, jqXHR) {
                                if ('message' in data)
                                    display_message(data.message, "info");
                                else if ('redirect' in data)
                                    window.location.replace(data.redirect);
                                else
                                    alert("strange data receieved from flagging a message: " + data);
                            })
                })

                $("#answer-{{ my_answer_id}}").hover(function () {
                    $("#edit-answer-{{my_answer_id}}").show();
                }, function () {
                    $("#edit-answer-{{my_answer_id}}").hide();
                });

                {% if max_length_a_content %}
                    var $answerContent = $("#id_content"),
                            $charsCounter = $("#charsCounter"),
                            $charsLeft = $("#charsLeft");

                    $charsCounter.hide();
                    $answerContent.on("keyup", function () {
                        var length = this.value.length;

                        if (length) $charsCounter.show();
                        else $charsCounter.hide();

                        $charsLeft.text({{ max_length_a_content }} -length);
                    });
                {% endif %}
            });
        </script>
    {% endblock %}
{% endif %}